### ISSUE TITLE
Boot error

### ISSUE THREAD

**Issue by rusnazip** [gabrielmaialva33/efi-opencore-z97p#1]
When i try boot i get error
00:000 00:000 OC: Tool Tools\OpenHfsPlus.efi cannot be found!
00:062 00:062 OCB: LoadImage failed - Not Found
04:667 04:605 OC: Tool Tools\VBoxHfs.efi cannot be found!
04:691 00:024 OCB: LoadImage failed - Not Found

**Comment by gabrielmaialva33** [comment]
Sorry, an update has been made to the repo. Try.. try again..
