### ISSUE TITLE
Very slow boot on 12.2.1

### ISSUE THREAD

**Issue by Elektronenhirn108** [gabrielmaialva33/efi-opencore-z97p#2]
Hello,

I think since 12.2 my macOS boot is verrrry slow. I haven't changed anything. Can you please share your BIOS-Settings? Do you have any other ideas what could cause the slow boot? I already removed all debug flags.

I would very much appreciate your help.

**Comment by gabrielmaialva33** [comment]
Sorry, an update has been made to the repo. Try.. try again..

**Comment by Elektronenhirn108** [comment]
Thank you. Have you already been messing around with macOS 13?
